return {
    text = {
        { t = "Feed",        x = 46,  y = 11, to = SMLSIZE },
        { t = "forward",     x = 38,  y = 18, to = SMLSIZE },
        { t = "D",           x = 86,  y = 11, to = SMLSIZE },
        { t = "Min",         x = 81,  y = 18, to = SMLSIZE },
        { t = "ROLL",        x = 8,   y = 26, to = SMLSIZE },
        { t = "PITCH",       x = 8,   y = 36, to = SMLSIZE },
        { t = "YAW",         x = 8,   y = 46, to = SMLSIZE },
        { t = "Feedforward", x = 110, y = 14, to = SMLSIZE },
        { t = "Transition",  x = 120, y = 22, to = SMLSIZE },
        { t = "D Min",       x = 110, y = 30, to = SMLSIZE },
        { t = "Gain",        x = 120, y = 38, to = SMLSIZE },
        { t = "Advance",     x = 120, y = 46, to = SMLSIZE },
    },
    fields = {
        { x = 49,  y = 26, min = 0, max = 2000, vals = { 33, 34 }, to = SMLSIZE },
        { x = 49,  y = 36, min = 0, max = 2000, vals = { 35, 36 }, to = SMLSIZE },
        { x = 49,  y = 46, min = 0, max = 2000, vals = { 37, 38 }, to = SMLSIZE },
        { x = 81,  y = 26, min = 0, max = 100,  vals = { 40 },     to = SMLSIZE },
        { x = 81,  y = 36, min = 0, max = 100,  vals = { 41 },     to = SMLSIZE },
        { x = 81,  y = 46, min = 0, max = 100,  vals = { 42 },     to = SMLSIZE },
        { x = 180, y = 22, min = 0, max = 100,  vals = { 9 },      to = SMLSIZE, scale = 100 },
        { x = 180, y = 38, min = 0, max = 100,  vals = { 43 },     to = SMLSIZE },
        { x = 180, y = 46, min = 0, max = 200,  vals = { 44 },     to = SMLSIZE },
    },
}
