changelog:
  exclude:
    labels:
      - "cleanup"
      - "RN: IGNORE"
  categories:
    - title: Features
      labels:
        - "RN: FEATURE"
        - "RN: MAJOR FEATURE"
        - "RN: MINOR FEATURE"
    - title: Improvements
      labels:
        - "RN: IMPROVEMENT"
        - "RN: UI"
        - "RN: REFACTOR"
        - "RN: FONT"
    - title: Fixes
      labels: 
        - "RN: BUGFIX"
    - title: Translation
      labels: 
        - "RN: TRANSLATION"
    - title: Known Issues
      labels:
        - BUG
