return {
    labels = {
        { t = "Gyro Lowpass 1 Dynamic",   x = 2,  y = 12,  },
        { t = "Min Cutoff",               x = 12, y = 20,  },
        { t = "Max Cutoff",               x = 12, y = 28,  },
        { t = "Filter Type",              x = 12, y = 36,  },
        { t = "Gyro Lowpass 1",           x = 2,  y = 44,  },
        { t = "Cutoff",                   x = 12, y = 52,  },
        { t = "Filter Type",              x = 12, y = 60,  },
        { t = "Gyro Lowpass 2",           x = 2,  y = 68,  },
        { t = "Cutoff",                   x = 12, y = 76,  },
        { t = "Filter Type",              x = 12, y = 84,  },
        { t = "Gyro Notch 1",             x = 2,  y = 92,  },
        { t = "Center",                   x = 12, y = 100, },
        { t = "Cutoff",                   x = 12, y = 108, },
        { t = "Gyro Notch 2",             x = 2,  y = 116, },
        { t = "Center",                   x = 12, y = 124, },
        { t = "Cutoff",                   x = 12, y = 132, },
        { t = "D Term Lowpass 1 Dynamic", x = 2,  y = 140, },
        { t = "Min Cutoff",               x = 12, y = 148, },
        { t = "Max Cutoff",               x = 12, y = 156, },
        { t = "Filter Type",              x = 12, y = 164, },
        { t = "D Term Lowpass 1",         x = 2,  y = 172, },
        { t = "Cutoff",                   x = 12, y = 180, },
        { t = "Filter Type",              x = 12, y = 188, },
        { t = "D Term Lowpass 2",         x = 2,  y = 196, },
        { t = "Cutoff",                   x = 12, y = 204, },
        { t = "Filter Type",              x = 12, y = 212, },
        { t = "D Term Notch",             x = 2,  y = 220, },
        { t = "Center",                   x = 12, y = 228, },
        { t = "Cutoff",                   x = 12, y = 236, },
        { t = "Yaw Lowpass",              x = 2,  y = 244, },
        { t = "Cutoff",                   x = 12, y = 252, },
    },
    fieldLayout = {
        { x = 87, y = 20, },
        { x = 87, y = 28, },
        { x = 87, y = 36, },
        { x = 87, y = 52, },
        { x = 87, y = 60, },
        { x = 87, y = 76, },
        { x = 87, y = 84, },
        { x = 87, y = 100, },
        { x = 87, y = 108, },
        { x = 87, y = 124, },
        { x = 87, y = 132, },
        { x = 87, y = 148, },
        { x = 87, y = 156, },
        { x = 87, y = 164, },
        { x = 87, y = 180, },
        { x = 87, y = 188, },
        { x = 87, y = 204, },
        { x = 87, y = 212, },
        { x = 87, y = 228, },
        { x = 87, y = 236, },
        { x = 87, y = 252, },
    }
}
