return {
    yMinLimit      = 11,
    yMaxLimit      = 52,
    text = {
        { t = "Feed",        x = 45,  y = 11, },
        { t = "forward",     x = 37,  y = 18, },
        { t = "D",           x = 85,  y = 11, },
        { t = "Min",         x = 80,  y = 18, },
        { t = "ROLL",        x = 10,  y = 26, },
        { t = "PITCH",       x = 10,  y = 36, },
        { t = "YAW",         x = 10,  y = 46, },
        { t = "Feedforward", x = 10,  y = 60, },
        { t = "Transition",  x = 20,  y = 68, },
        { t = "D Min",       x = 10,  y = 76, },
        { t = "Gain",        x = 20,  y = 84, },
        { t = "Advance",     x = 20,  y = 92, },
    },
    fieldLayout = {
        { x = 48, y = 26, },
        { x = 48, y = 36, },
        { x = 48, y = 46, },
        { x = 80, y = 26, },
        { x = 80, y = 36, },
        { x = 80, y = 46, },
        { x = 80, y = 68, },
        { x = 80, y = 84, },
        { x = 80, y = 92, },
    },
}
