return {
    labels = {
        { t = "Feed",        x = 45,  y = 12, },
        { t = "forward",     x = 37,  y = 20, },
        { t = "D",           x = 85,  y = 12, },
        { t = "Min",         x = 80,  y = 20, },
        { t = "ROLL",        x = 10,  y = 28, },
        { t = "PITCH",       x = 10,  y = 38, },
        { t = "YAW",         x = 10,  y = 48, },
        { t = "Feedforward", x = 10,  y = 60, },
        { t = "Transition",  x = 20,  y = 68, },
        { t = "D Min",       x = 10,  y = 76, },
        { t = "Gain",        x = 20,  y = 84, },
        { t = "Advance",     x = 20,  y = 92, },
    },
    fieldLayout = {
        { x = 48, y = 28, },
        { x = 48, y = 38, },
        { x = 48, y = 48, },
        { x = 80, y = 28, },
        { x = 80, y = 38, },
        { x = 80, y = 48, },
        { x = 80, y = 68, },
        { x = 80, y = 84, },
        { x = 80, y = 92, },
    },
}