return {
   labels = {
      { t = "Min Sats.",      x =  3,  y = 12, },
      { t = "Angle",          x =  3,  y = 22, },
      { t = "Initial Alt",    x =  3,  y = 32, },
      { t = "Descent Dst",    x =  3,  y = 42, },
      { t = "Ground Spd",     x =  3,  y = 52, },
      { t = "Snty.",          x =  80, y = 12, },
      { t = "Throttle",       x =  80, y = 22, },
      { t = "Min",            x =  85, y = 32, },
      { t = "Hover",          x =  80, y = 42, },
      { t = "Max",            x =  85, y = 52, },
   },
   fieldLayout = {
      { x = 58, y = 12,  },
      { x = 58, y = 22,  },
      { x = 58, y = 32,  },
      { x = 58, y = 42,  },
      { x = 58, y = 52,  },
      { x = 105, y = 12, },
      { x = 105, y = 32, },
      { x = 105, y = 42, },
      { x = 105, y = 52, },
   },
}
