return {
    text = {
        { t = "Acro Trainer",      x = 2,  y = 12,  },
        { t = "Angle Limit",       x = 12, y = 20,  },
        { t = "Throttle Boost",    x = 2,  y = 28,  },
        { t = "Absolute Control",  x = 2,  y = 36,  },
        { t = "I Term Rotation",   x = 2,  y = 44,  },
        { t = "VBAT Compensation", x = 2,  y = 52,  },
        { t = "I Term Relax",      x = 2,  y = 60,  },
        { t = "Axes",              x = 12, y = 68,  },
        { t = "Type",              x = 12, y = 76,  },
        { t = "Integrated Yaw",    x = 2,  y = 84,  },
        { t = "Anti Gravity",      x = 2,  y = 92,  },
        { t = "Mode",              x = 12, y = 100, },
        { t = "Gain",              x = 12, y = 108, },
        { t = "Threshold",         x = 12, y = 116, },
    },
    fieldLayout = {
        { x = 87, y = 20,  },
        { x = 87, y = 28,  },
        { x = 87, y = 36,  },
        { x = 87, y = 44,  },
        { x = 87, y = 52,  },
        { x = 87, y = 68,  },
        { x = 87, y = 76,  },
        { x = 87, y = 84,  },
        { x = 87, y = 100, },
        { x = 87, y = 108, },
        { x = 87, y = 116, },
    }
}
