return {
    text = {
        { t = "Feed",        x = 46,  y = 11, },
        { t = "forward",     x = 38,  y = 18, },
        { t = "D",           x = 86,  y = 11, },
        { t = "Min",         x = 81,  y = 18, },
        { t = "ROLL",        x = 8,   y = 26, },
        { t = "PITCH",       x = 8,   y = 36, },
        { t = "YAW",         x = 8,   y = 46, },
        { t = "Feedforward", x = 110, y = 14, },
        { t = "Transition",  x = 120, y = 22, },
        { t = "D Min",       x = 110, y = 30, },
        { t = "Gain",        x = 120, y = 38, },
        { t = "Advance",     x = 120, y = 46, },
    },
    fieldLayout = {
        { x = 49,  y = 26, },
        { x = 49,  y = 36, },
        { x = 49,  y = 46, },
        { x = 81,  y = 26, },
        { x = 81,  y = 36, },
        { x = 81,  y = 46, },
        { x = 180, y = 22, },
        { x = 180, y = 38, },
        { x = 180, y = 46, },
    },
}
